### ISSUE TITLE
always returns array of results

### ISSUE THREAD

**Issue by world** [gberger/mongoose-named-scopes#1]
I love this package. So simple and brilliant. Question: all results of scopes return array even if I set limit(1). Is there anyway to use this package and have it findOne and return a single result instead of [resutls]?

**Comment by gberger** [comment]
I think that if your named scopes do not use `find`, you can do this:

```
User.findOne().olderThan(20)
```

You can avoid using `find` by using `where` in your scopes.

If they do use find, I believe you can just append `findOne` at the end of the chain:

```
User.olderThan(20).findOne()
```

Let me know if these solutions work!

**Comment by world** [comment]
Brilliant. Both your suggestions worked (putting findOne() at begging or end of query). Luckily my scopes used where anyway, so all good there.

Hey, I think it would be helpful for other users (like myself) who don't know mongoose's chaining so well, to put this in the README. If you agree I will do it via pull request. Lmk. 

Again, dude, you rock. Most concise code i have ever seen. How long did it take you to do this? If you tell me one hour I am going to have to punch you. :)

**Comment by world** [comment]
PS I like the way we think:
https://github.com/gberger/dotfiles
https://github.com/world/dotfiles

**Comment by gberger** [comment]
I agree, please send over your PR! :)

Thanks for the kind words 😊 

It was 8h from when I posted the question until my first working commit, but I think I worked on it for about 2:30h?

Oh, I think your dotfiles are private 😛

**Comment by gberger** [comment]
I updated the readme already

**Comment by world** [comment]
damn dude you got crazy skillz. How long you been coding? I love this package. The updates you made to it are nice. Now, I am prob too n00b to understand the value of some of it... but I really like being able to chain the scopes and pass predicate functions for fine tuning.

**Comment by gberger** [comment]
Thanks @world :)

I've been coding for ~4 years now. Just about to graduate college.

To chain the scopes, I made use of the Proxy object that is new in ES6. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy
