### ISSUE TITLE
Discriminators: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by black-roland** [gberger/mongoose-named-scopes#3]
Hi.

Unfortunately scopes does not work with [discriminators](http://mongoosejs.com/docs/discriminators.html) :( I get error when call scope in inherited model:

```
TypeError: Cannot read property 'apply' of undefined
  at Query.(anonymous function) [as published] (/.../node_modules/mongoose-named-scopes/index.js:74:19)
```

**Comment by gberger** [comment]
Oh :( Sorry, I haven't used that feature before. Can you paste a small snippet that reproduces the error?

**Comment by gberger** [comment]
Nevermind, fixed on v1.0.1

https://github.com/gberger/mongoose-named-scopes/commit/645fb219ec38ab49e68e600676131bbc28fac8e7

**Comment by gberger** [comment]
@black-roland let me know if you still have issues

**Comment by black-roland** [comment]
Everything works perfectly. Thank you!
